import 'package:flutter/material.dart';
import 'package:lucide_icons/lucide_icons.dart';

// Key -> {label, icon}
// Using generic icons for now. In a real app with uniform 3D assets,
// we would replace 'icon' with 'assetPath'.
final Map<String, Map<String, dynamic>> APP_CATEGORIES = {
  'all': {
    'id': 'all',
    'label': 'Todos',
    'en_label': 'All',
    'icon': LucideIcons.layoutGrid,
    'color': Colors.grey,
    'types': ['all'],
  },
  // --- FOOD ---
  'burgers': {
    'id': '327606c4-16e4-42b6-8f8d-b9148d6f3838',
    'label': 'Burgers',
    'en_label': 'Burgers',
    'icon': LucideIcons.sandwich, // Closest icon
    'color': Colors.orangeAccent,
    'types': ['restaurant', 'dark_kitchen', 'snack_bar'],
  },
  'fast_food': {
    'id': '7df9a4ad-3f87-480f-975b-28230153c2f4',
    'label': 'Fast food',
    'en_label': 'Fast Food',
    'icon': LucideIcons.utensils,
    'color': const Color(0xFFE63946),
    'types': ['restaurant', 'dark_kitchen'],
  },
  'pizza': {
    'id': 'fa7cbd82-c463-47e3-b813-444793a3144a',
    'label': 'Pizzas',
    'en_label': 'Pizzas',
    'icon': LucideIcons.pizza,
    'color': Colors.orange,
    'types': ['restaurant', 'pizzeria'],
  },
  'sushi': {
    'id': 'cb839d56-fb6a-40bd-9830-bbff9f5275ba',
    'label': 'Sushi',
    'en_label': 'Sushi',
    'icon': LucideIcons.fish,
    'color': Colors.redAccent,
    'types': ['restaurant', 'japanese'],
  },
  'bbq': {
    'id': 'd48c9e17-fa5c-4571-8564-f0a593f12944',
    'label': 'Churrasco',
    'en_label': 'BBQ',
    'icon': LucideIcons.flame,
    'color': Colors.brown,
    'types': ['restaurant', 'steakhouse'],
  },
  'sandwiches': {
    'id': 'e4834752-7fa4-4e4f-9153-59f72077728c',
    'label': 'Sanduíches',
    'en_label': 'Sandwiches',
    'icon': LucideIcons.sandwich,
    'color': Colors.amber,
    'types': ['restaurant', 'bakery', 'cafe'],
  },
  'vegan': {
    'id': '83667288-e8fc-46dd-8565-37b4eaf92fba',
    'label': 'Vegano',
    'en_label': 'Vegan',
    'icon': LucideIcons.leaf,
    'color': Colors.green,
    'types': ['restaurant'],
  },
  'dessert': {
    'id': '1113c888-9859-4291-ba6e-359319a7cfa2',
    'label': 'Sobremesas',
    'en_label': 'Desserts',
    'icon': LucideIcons.iceCream2,
    'color': Colors.purple,
    'types': ['restaurant', 'bakery', 'ice_cream'],
  },
  'italian': {
    'id': '2921be16-ca80-4a37-835b-ed77dbcc3e6b',
    'label': 'Italiana',
    'en_label': 'Italian',
    'icon': LucideIcons.chefHat,
    'color': Colors.redAccent,
    'types': ['restaurant'],
  },
  'japanese': {
    'id': '6446f21d-79b0-4b50-89a9-113ffc6a3e46',
    'label': 'Japonesa',
    'en_label': 'Japanese',
    'icon': LucideIcons.soup,
    'color': Colors.red,
    'types': ['restaurant'],
  },
  'chinese': {
    'id': '4593d393-453d-4658-af9e-5ca4904e8ad7',
    'label': 'Chinesa',
    'en_label': 'Chinese',
    'icon': LucideIcons.utensilsCrossed,
    'color': Colors.red[900],
    'types': ['restaurant'],
  },
  'brazilian': {
    'id': '5b54f7d7-9d4d-4c15-963c-1d29fdcee239',
    'label': 'Brasileira',
    'en_label': 'Brazilian',
    'icon': LucideIcons.flame,
    'color': Colors.green[700],
    'types': ['restaurant'],
  },
  'portuguese': {
    'id': 'aac0718c-6ac2-4786-ac2d-77f6c5f83604',
    'label': 'Portuguesa',
    'en_label': 'Portuguese',
    'icon': LucideIcons.wine,
    'color': Colors.deepPurple,
    'types': ['restaurant'],
  },
  'mexican': {
    'id': 'e2c84d88-ee21-4a4d-a941-df8c0a0157b4',
    'label': 'Mexicana',
    'en_label': 'Mexican',
    'icon': LucideIcons.sun,
    'color': Colors.orange[800],
    'types': ['restaurant'],
  },
  'healthy': {
    'id': '34491092-3ef3-4370-a965-e279639ae0f2',
    'label': 'Saudável',
    'en_label': 'Healthy',
    'icon': LucideIcons.apple,
    'color': Colors.lightGreen,
    'types': ['restaurant'],
  },
  'pastry': {
    'id': 'ee4f4efc-2ca6-4221-8718-d1d0e91b427f',
    'label': 'Pastelaria',
    'en_label': 'Pastry',
    'icon': LucideIcons.croissant,
    'color': Colors.amber[200],
    'types': ['restaurant', 'bakery'],
  },
  'seafood': {
    'id': 'bba723ef-715b-4039-9397-8b5a24a3d567',
    'label': 'Peixes',
    'en_label': 'Seafood',
    'icon': LucideIcons.fish,
    'color': Colors.lightBlue,
    'types': ['restaurant'],
  },
  'vegetarian': {
    'id': 'a1bf7f4b-1e86-487c-ab6f-7250432f6983',
    'label': 'Vegetariana',
    'en_label': 'Vegetarian',
    'icon': LucideIcons.carrot,
    'color': Colors.green,
    'types': ['restaurant'],
  },

  // --- PHARMACY ---
  'medication': {
    'id': 'pharmacy_meds',
    'label': 'Medicamentos',
    'en_label': 'Medication',
    'icon': LucideIcons.pill,
    'color': Colors.red,
    'types': ['pharmacy'],
  },
  'hygiene': {
    'id': 'pharmacy_hygiene',
    'label': 'Higiene',
    'en_label': 'Hygiene',
    'icon': LucideIcons.bath,
    'color': Colors.blue,
    'types': ['pharmacy', 'market'],
  },
  'cosmetics': {
    'id': 'pharmacy_cosmetics',
    'label': 'Cosméticos',
    'en_label': 'Cosmetics',
    'icon': LucideIcons.sparkles,
    'color': Colors.pink,
    'types': ['pharmacy'],
  },
  'baby': {
    'id': 'pharmacy_baby',
    'label': 'Bebê',
    'en_label': 'Baby',
    'icon': LucideIcons.baby,
    'color': Colors.purpleAccent,
    'types': ['pharmacy', 'market'],
  },
  'supplements': {
    'id': 'pharmacy_supplements',
    'label': 'Suplementos',
    'en_label': 'Supplements',
    'icon': LucideIcons.dumbbell,
    'color': Colors.orangeAccent,
    'types': ['pharmacy'],
  },
  'first_aid': {
    'id': 'pharmacy_first_aid',
    'label': 'Primeiros Socorros',
    'en_label': 'First Aid',
    'icon': LucideIcons.heartPulse,
    'color': Colors.redAccent,
    'types': ['pharmacy'],
  },

  // --- BEVERAGES / BREWERY ---
  'drinks': {
    'id': '0fa83a66-5b37-4d62-9426-a9c1d40ee859',
    'label': 'Bebidas',
    'en_label': 'Drinks',
    'icon': LucideIcons.beer,
    'color': Colors.blue,
    'types': ['restaurant', 'beverages'],
  },
  'beer': {
    'id': 'bev_beer',
    'label': 'Cervejas',
    'en_label': 'Beer',
    'icon': LucideIcons.beer,
    'color': Colors.amber[800],
    'types': ['beverages', 'restaurant'],
  },
  'wine': {
    'id': 'bev_wine',
    'label': 'Vinhos',
    'en_label': 'Wine',
    'icon': LucideIcons.wine,
    'color': Colors.purple[800],
    'types': ['beverages', 'restaurant'],
  },
  'spirits': {
    'id': 'bev_spirits',
    'label': 'Destilados',
    'en_label': 'Spirits',
    'icon': LucideIcons.glassWater,
    'color': Colors.indigo,
    'types': ['beverages', 'restaurant'],
  },
  'soda': {
    'id': 'bev_soda',
    'label': 'Refrigerantes',
    'en_label': 'Soda',
    'icon': LucideIcons.cupSoda,
    'color': Colors.red,
    'types': ['beverages', 'restaurant'],
  },
  'water': {
    'id': 'bev_water',
    'label': 'Água',
    'en_label': 'Water',
    'icon': LucideIcons.droplet,
    'color': Colors.blue[300],
    'types': ['beverages', 'restaurant', 'pharmacy'],
  },
  'juice': {
    'id': 'bev_juice',
    'label': 'Sucos',
    'en_label': 'Juice',
    'icon': LucideIcons.citrus,
    'color': Colors.orange,
    'types': ['beverages', 'restaurant'],
  },
  'energy': {
    'id': 'bev_energy',
    'label': 'Energéticos',
    'en_label': 'Energy Drinks',
    'icon': LucideIcons.zap,
    'color': Colors.yellow[700],
    'types': ['beverages', 'market'],
  },
  'ice': {
    'id': 'bev_ice',
    'label': 'Gelo',
    'en_label': 'Ice',
    'icon': LucideIcons.snowflake,
    'color': Colors.cyan,
    'types': ['beverages', 'market'],
  },

  // Specific Beers (for Brewery)
  'ipa': {
    'id': 'beer_ipa',
    'label': 'IPA',
    'en_label': 'IPA',
    'icon': LucideIcons.hop,
    'color': Colors.green[800],
    'types': ['beverages'],
  },
  'lager': {
    'id': 'beer_lager',
    'label': 'Lager',
    'en_label': 'Lager',
    'icon': LucideIcons.beer,
    'color': Colors.amber,
    'types': ['beverages'],
  },
  'stout': {
    'id': 'beer_stout',
    'label': 'Stout / Preta',
    'en_label': 'Stout',
    'icon': LucideIcons.coffee,
    'color': Colors.black,
    'types': ['beverages'],
  },
  'wheat': {
    'id': 'beer_wheat',
    'label': 'Trigo / Weiss',
    'en_label': 'Wheat',
    'icon': LucideIcons.wheat,
    'color': Colors.amber[200],
    'types': ['beverages'],
  },
  'apa': {
    'id': 'beer_apa',
    'label': 'APA',
    'en_label': 'APA',
    'icon': LucideIcons.hop,
    'color': Colors.orange,
    'types': ['beverages'],
  },
  'belgian': {
    'id': 'beer_belgian',
    'label': 'Belgian',
    'en_label': 'Belgian',
    'icon': LucideIcons.beer,
    'color': Colors.amberAccent,
    'types': ['beverages'],
  },
  'dark_beer': {
    'id': 'beer_dark',
    'label': 'Escura / Malzbier',
    'en_label': 'Dark Beer',
    'icon': LucideIcons.coffee,
    'color': Colors.brown[900],
    'types': ['beverages'],
  },

  // Spirits / Destilados specifics
  'vodka': {
    'id': 'spirit_vodka',
    'label': 'Vodka',
    'en_label': 'Vodka',
    'icon': LucideIcons.glassWater,
    'color': Colors.blueGrey,
    'types': ['beverages'],
  },
  'cachaca': {
    'id': 'spirit_cachaca',
    'label': 'Cachaça / Pinga',
    'en_label': 'Cachaça',
    'icon': LucideIcons.wine,
    'color': Colors.green[300],
    'types': ['beverages'],
  },
  'whiskey': {
    'id': 'spirit_whiskey',
    'label': 'Whiskey',
    'en_label': 'Whiskey',
    'icon': LucideIcons.glassWater,
    'color': Colors.brown,
    'types': ['beverages'],
  },
  'gin': {
    'id': 'spirit_gin',
    'label': 'Gin',
    'en_label': 'Gin',
    'icon': LucideIcons.glassWater,
    'color': Colors.cyan[100],
    'types': ['beverages'],
  },
  'tequila': {
    'id': 'spirit_tequila',
    'label': 'Tequila',
    'en_label': 'Tequila',
    'icon': LucideIcons.sun,
    'color': Colors.orange[300],
    'types': ['beverages'],
  },
  'liqueur': {
    'id': 'spirit_liqueur',
    'label': 'Licor',
    'en_label': 'Liqueur',
    'icon': LucideIcons.candy,
    'color': Colors.pinkAccent,
    'types': ['beverages'],
  },

  // --- BUTCHER / AÇOUGUE ---
  'butcher': {
    'id': 'butcher_meat',
    'label': 'Carnes',
    'en_label': 'Meats',
    'icon': LucideIcons.beef,
    'color': Colors.red[900],
    'types': ['market', 'butcher'],
  },
  'picanha': {
    'id': 'meat_picanha',
    'label': 'Picanha',
    'en_label': 'Picanha',
    'icon': LucideIcons.beef,
    'color': Colors.redAccent,
    'types': ['market', 'butcher'],
  },
  'rump_steak': {
    'id': 'meat_alcatra',
    'label': 'Alcatra',
    'en_label': 'Rump Steak',
    'icon': LucideIcons.beef,
    'color': Colors.red,
    'types': ['market', 'butcher'],
  },
  'ribs': {
    'id': 'meat_costela',
    'label': 'Costela',
    'en_label': 'Ribs',
    'icon': LucideIcons.bone,
    'color': Colors.brown,
    'types': ['market', 'butcher'],
  },
  'chicken': {
    'id': 'meat_chicken',
    'label': 'Frango',
    'en_label': 'Chicken',
    'icon': LucideIcons.drumstick,
    'color': Colors.orangeAccent,
    'types': ['market', 'butcher'],
  },
  'pork': {
    'id': 'meat_pork',
    'label': 'Suíno',
    'en_label': 'Pork',
    'icon': LucideIcons.piggyBank, // Closest to pig
    'color': Colors.pink[200],
    'types': ['market', 'butcher'],
  },
  'sausage': {
    'id': 'meat_sausage',
    'label': 'Linguiça',
    'en_label': 'Sausage',
    'icon': LucideIcons.search, // Generic
    'color': Colors.red[300],
    'types': ['market', 'butcher'],
  },

  // --- CUSTOM / OTHER ---
  'custom': {
    'id': 'custom_other',
    'label': 'Outros / Personalizado',
    'en_label': 'Other / Custom',
    'icon': LucideIcons.edit3,
    'color': Colors.grey,
    'types': ['all'],
  },
};
